### ISSUE TITLE
Export SignedTx

### ISSUE THREAD

**Issue by gidonkatten** [randlabs/myalgo-connect#14]
The `signTransaction` method returns `Promise<SignedTx | SignedTx[]>` however the interface `SignedTx` is not exported.

This means that I need to check if `blob` is a member of the returned value when it would be easier to just tell the compiler the type.

**Comment by Alex99y** [comment]
Hello @gidonkatten ! Thanks for reporting this issue. #16 
In few hours I will merge and update the package to v1.0.1

**Comment by Alex99y** [comment]
Done. Please update MyAlgo Connect package:
`npm i @randlabs/myalgo-connect@1.0.1`
