### ISSUE TITLE
Error: Invalid txn type

### ISSUE THREAD

**Issue by gidonkatten** [randlabs/myalgo-connect#15]
For some reason I keep on getting this error when trying to call an application. I cannot seem to diagnose the issue.

Relevant code is:
```
const buyer: string = addresses[0];

let params: SuggestedParams = await client.getTransactionParams().do();
params.fee = 1000;
params.flatFee = true;

const buy: Base64 = "buy";
const appArgs: Base64[] = [buy];
let callAppTxn: CallApplTxn = {
    ...params,
    type: "appl",
    from: buyer,
    appIndex: appId,
    appOnComplete: 0,
    appArgs: appArgs
}

let rawSignedCallAppTxn = await myAlgoWallet.signTransaction(callAppTxn) as TxSig;
```

The error occurs when signing the transaction. The pop up window appears (blank) for a split second and then I get the error `Unhandled Rejection (Error): Invalid txn type` from `node_modules/@randlabs/myalgo-connect/lib/main.js:311`.

Thanks in advance!

**Comment by Alex99y** [comment]
@gidonkatten thanks for reporting!. Please try again, we solved the problem.

**Comment by gidonkatten** [comment]
Thanks, it now is working. What was the issue if you don't mind me asking?

**Comment by gidonkatten** [comment]
Not sure where the best place to ask general questions so please let me know.

How would you recommend dealing with persistent accounts such that users do not have to connect each time they visit a site? From my understanding from reading the code, all one has to do is store the public addresses. I also see that `myalgo` has in settings `connected sites` so what is the role of that as well?

**Comment by Alex99y** [comment]
> Thanks, it now is working. What was the issue if you don't mind me asking?

We are releasing partially MyAlgo Connect features. 

> How would you recommend dealing with persistent accounts such that users do not have to connect each time they visit a site? From my understanding from reading the code, all one has to do is store the public addresses. I also see that myalgo has in settings connected sites so what is the role of that as well?

Exactly. We expect that the dApp stores the user's public addresses.

**Comment by Alex99y** [comment]
Currently, we only allow the user to update his shared accounts in the MyAlgo Connect - Unlock popup. You can find this option in the top-right of the popup, it is a Gear icon. Before updating the shared account, you must provide the password.
