### ISSUE TITLE
Have to disconnect site to add new address

### ISSUE THREAD

**Issue by gidonkatten** [randlabs/myalgo-connect#17]
When you re-connect the addresses to a website that has already been connected in the past (and therefore is in `myalgo` `connected sites` in settings), there is no option / check for new wallets. You have to disconnect the site to add the new wallet address.

To reproduce:
1.  call `new MyAlgo().connect()`
2.  create new wallet on myalgo
3.  call `new MyAlgo().connect()`

**Comment by Alex99y** [comment]
Currently, we only allow the user to update his shared accounts in the MyAlgo Connect - Unlock popup. You can find this option in the top-right of the popup, it is a Gear icon. Before updating the shared account, you must provide the password.
