### ISSUE TITLE
Critical bug in Myalgo web wallet due to caching of ALGO public-key/address in Algorand ledger app

### ISSUE THREAD

**Issue by loupiote** [randlabs/myalgo-connect#20]
Just making sure that you get aware of the critical bug reported here:

https://www.reddit.com/r/ledgerwallet/comments/mb9brr/psa_do_not_use_algo_with_the_ledger_via_the_algo/

You should never cache the ALGO account address in the Algorand ledger app, because the ledger seed is not always the same:

A user can use a BIP39 passphrase and this will generate different seeds (with the active/unlocked seed being derived from the currently used passphrase - or empty passphrase if none is used).

The bug is critical and can cause permanent loss of ALGO coins and tokens.

Note: this bug also affects https://algorandwallet.com/ , but I cannot find their Github to report it.

**Comment by Alex99y** [comment]
This problem's not related to MyAlgo Connect. Currently, Algorand Foundation is finding a solution for this bug.

**Comment by loupiote** [comment]
Yes, I know: This issue is in the Algorand app on the ledger, which is queried by MyAlgo.

**Comment by loupiote** [comment]
By the way, what is the derivation path for ALGO account #n derived from the seed?

I could not find the derivation path info on MyAlgo not anywhere else. I know I could probably capture the USB communication or search in the source code to find that, but simple to ask here maybe....

This is important info that should be made public, in case there are issues recovering access to old accounts, in the future (I know several cryptos that had to change their derivation path, causing problems with legacy accounts (e.g. ETH, FLOW).

**Comment by Alex99y** [comment]
@loupiote  Currently, MyAlgo does not ask for a specific derivation path, we just call the operation `INS_GET_PUBLIC_KEY` and by default, Algorand App gives us the first account.

https://github.com/algorand/ledger-app-algorand/blob/520b4987340b839d94457cf420bb72f6f5a09815/src/main.c#L280
https://github.com/algorand/ledger-app-algorand/blob/520b4987340b839d94457cf420bb72f6f5a09815/src/algo_keys.c#L9
