### ISSUE TITLE
Unable to recover access to an Algorand account by entering my BIP39 mnemonic (+ optional passphrase)  in MyAlgo

### ISSUE THREAD

**Issue by loupiote** [randlabs/myalgo-connect#21]
Unable to recover access to an Algorand account by entering my BIP39 mnemonic (+ optional passphrase)  in MyAlgo web wallet.

There seems to be no way to enter a 12, 18 or 24 word (+ optional passphrase) BIP39 mnemonic in MyAlgo to recover access to an Algorand account.

Same issue with the "Official Algorand phone wallet", by the way.

Does MyAlgo use a proprietary mnemonic format (not compatible with BIP39)?

Any plan to support the BIP39 standard recovery mnemonic format (12, 18 or 24 word + optional passphrase), which now-a-days are supported by almost all crypto wallets for seed recovery?

[EDITED]

Apparently Algorand wallets use a proprietary recovery phrase that directly encode the keys: https://discord.com/channels/491256308461207573/631209441240416256/812841568620642354

 _Algorand does not use at all BIP39 
 The mnemonic directly encodes the key._ 
 
Algorand wallets should add support for recovery from standard BIP39 seeds (from BIP39 mnemonic and optional passphrase), and then derive the ALGO keys using the standard ALGO derivation path, m/44'/283'/x'/0/0 for account #x.

**Comment by mxmauro** [comment]
Hi @loupiote we already forwarded it to the Algorand's Ledger App team.

Thanks.

**Comment by loupiote** [comment]
I think that, as a temporary solution, there should be a software tool to obtain the ALGO private key (represented in the proprietary 25-word format) derived from a given BIP39 seed and a given derivation path (e.g. m/44'/283'/x'/0/0 for account #x). This would allow ALGO account recovery using the Algorand software wallets.

The BIP39 seed could be provided as a BIP39 mnemonic and optional passphrase, or just simply as a hex-digest for a 512-bit BIP39 seed value, since there is already existing tools (e.g. the Ian Coleman BIP39 tool) to get the hex-digest of the BIP39 seed from mnemonic and passphrase.

Such a tool would be sufficient to recover access to ALGO accounts that were created with a Ledger, using Algorand software wallet private-key recovery.

**Comment by mxmauro** [comment]
That would violate the security and purpose of a hardware device.

**Comment by loupiote** [comment]
> That would violate the security and purpose of a hardware device.

Of course, this would be only for cases where the user does not have access to their ledger (e.g. device broken or unavailable / lost / stolen), and the user need immediate emergency access to their funds.

I personally feel very uncomfortable having a crypto account that is only accessible via the use of some proprietary hardware. All the other cryptos supported by the ledger device can be recovered (in case of emergency) using the BIP39 seed, via software wallets. There is even an article on the ledger website about this: https://support.ledger.com/hc/en-us/articles/115005297709-Export-your-accounts

Of course, I am an engineer, and I can read and write code, so I would be able to look at the open-source code of the Algorand ledger app ( https://github.com/algorand/ledger-app-algorand ) , and i am sure I could write a python script that does the BIP39 key derivation, and then the encoding of the Algo private key in the proprietary 25-word format used by the Algo wallets, and recover access to my ALGO, if needed. But the average Ledger user cannot do that, and they'd be screwed. And in some countries, it can take weeks or months to get another Ledger device.

There are a couple of other cryptos, like XLM, NEO and NANO, that have wallets that do not take BIP39 seed mnemonic for recovery , but rather just their private keys, and all those cryptos made scripts available to derive the private keys from the BIP39 seed, for emergency recovery. Hopefully Algorand dev team will do the same.

**Comment by nuhash** [comment]
Why was this closed?
This is just a request to fully support a standard that you already have partial support for...

**Comment by mxmauro** [comment]
Hi @nuhash the issue is not related to MyAlgo nor MyAlgo-Connect. It is related to Ledger App (https://github.com/algorand/ledger-app-algorand).

We forwarded the request as a suggestion because we don't own that project and we are not involved at all.
