### ISSUE TITLE
"Error: Not supported at MyAlgoConnect.signTransaction" when signing app create transaction

### ISSUE THREAD

**Issue by salgodev** [randlabs/myalgo-connect#25]
I keep getting `Error: Not supported at MyAlgoConnect.signTransaction` when signing an app create transaction, and it doesn't seem to matter which TEAL version I'm using.

Example code below:
```
let createApp = async () => {
  let accounts = await myAlgoWallet.connect();
  let params = await algodClient.getTransactionParams().do();

  let transaction = {
    from: accounts[0].address,
    type: 'appl',
    appOnComplete: 0,
    appApprovalProgram: "AiABASI=",
    appClearProgram: "AiABASI=",
    appLocalInts: 0,
    appLocalByteSlices: 0,
    appGlobalInts: 1,
    appGlobalByteSlices: 1,
    ...params
  };

  let signedTransaction = await myAlgoWallet.signTransaction(transaction);
}
```

Am I doing something wrong or is application create transactions really not supported?

Thanks!

**Comment by Alex99y** [comment]
@salgodev thanks for reporting. Today, we allowed signing create and update appl.

**Comment by salgodev** [comment]
Thanks @Alex99y! I've tried it out and it works perfectly!
