### ISSUE TITLE
Window blanks on icon hover

### ISSUE THREAD

**Issue by gidonkatten** [randlabs/myalgo-connect#28]
When signing a transaction, when my mouse hovers over the `i` information icon in the top right, the window goes completely white.

**Comment by Alex99y** [comment]
Hello @gidonkatten ! Thanks for reporting this issue. Can you provide an example transaction to produce this error?

**Comment by gidonkatten** [comment]
I think I figured out the problem. I am calling `algosdk.assignGroupID` and that is changing the genisis hash from a `string` to a `UInt8Array`. That causes the window to crash because it doesn't know how to display it.

**Comment by Alex99y** [comment]
@gidonkatten anyways this issue must be fixed on the popup side. Thank you a lot, once the bug is fixed I will let you know.

**Comment by Alex99y** [comment]
Fixed!
