### ISSUE TITLE
Augment MyAlgoAccount.connect() to return the account nickname

### ISSUE THREAD

**Issue by oysterpack** [randlabs/myalgo-connect#36]
Currently, the `MyAlgoAccount.connect()` API only returns the account Algorand addresses, which are not user-friendly. The account nickname that was assigned in the MyAlgo wallet should also be provided. The nickname would make it easier for the user to confirm and identify the Algorand address from within the app.

I propose to augment `Accounts` with a `nickname` field.

```typescript
export type Nickname = string;

export interface Accounts {
	address: Address;
        nickname: Nickname
}
```

**Comment by Alex99y** [comment]
Thanks for your feedback @oysterpack ! I agree with you, the next version of MyAlgo Connect will return the account name with the address.

**Comment by Alex99y** [comment]
Done, you can update MyAlgo Connect version to  1.1.0
