### ISSUE TITLE
Atomic transfer

### ISSUE THREAD

**Issue by Vidhyanandcs** [randlabs/myalgo-connect#37]
Hi, 
Can we do atomic transfers with my algo wallet?

**Comment by Alex99y** [comment]
Hello @Vidhyanandcs ! what do you mean by atomic transfers?. MyAlgo Connect is a tool for signing transactions using your credentials stored in MyAlgo Wallet.

**Comment by Vidhyanandcs** [comment]
Ok. So I can sign an atomic transfer which is a multi signature transaction. 

https://developer.algorand.org/docs/features/atomic_transfers/
