### ISSUE TITLE
I can't sign rekeyed account transactions

### ISSUE THREAD

**Issue by solkimicreb** [randlabs/myalgo-connect#38]
Hi and thanks for this awesome lib! I ran into a small issue.

**Preconditions**

I have two accounts:

- Main is a My Algo account
- Secondary is a fresh account that is immediately rekeyed to the My Algo Account

**Issue**

After the rekey the secondary account must be signed by the primary account's key but `myAlgoWallet.signTransaction(tx)` fails.

**Algosdk demo code**

```js
import algosdk from "algosdk";

const main = algosdk.mnemonicToSecretKey("mnemonic");
const secondary = algosdk.generateAccount();

export default async function makeRekeyedAccount() {
  const params = await algodclient.getTransactionParams().do();

  const fundTx = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
    suggestedParams: params,
    from: main.addr,
    to: secondary.addr,
    amount: 200000,
  });

  const rekeyTx = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
    suggestedParams: params,
    from: secondary.addr,
    to: secondary.addr,
    amount: 0,
    rekeyTo: main.addr,
  });

  const txs = [fundTx, rekeyTx];
  algosdk.assignGroupID(txs);

  const fundSigned = algosdk.signTransaction(fundTx, main.sk);
  const rekeySigned = algosdk.signTransaction(rekeyTx, secondary.sk);

  await client.sendRawTransaction([fundSigned.blob, rekeySigned.blob]).do();
}

export async function testTransaction() {
  const params = await algodclient.getTransactionParams().do();

  const testTx = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
    suggestedParams: params,
    // send a transaction from the secondary account which is already rekeyed to the main account
    from: secondary.addr,
    to: main.addr,
    amount: 0,
  });

  // the transaction has to be signed by the main account
  // this would fail if the main account would be a My Algo account and I used
  // `await myAlgoWallet.signTransaction(testTx)` here
  const testSigned = algosdk.signTransaction(testTx, main.sk);

  await client.sendRawTransaction(testSigned.blob).do();
}
```

There error is originating from here: https://github.com/randlabs/myalgo-connect/blob/f42ca7e52aa24a5cd98c6300ee6e5df8c9fda48e/lib/main.js#L305

![image](https://user-images.githubusercontent.com/6956014/122826104-0a785700-d2e3-11eb-8b50-79342e0c6490.png)
![image](https://user-images.githubusercontent.com/6956014/122826135-12d09200-d2e3-11eb-89d2-ff6b916659ec.png)

**Probable solution**

I guess you validate the transactions' `from` address and maybe forgot to check `account["auth-addr"]` against it.

**Comment by solkimicreb** [comment]
In case you are curious of the "real world usage". I am making a classic NFT marketplace and I plan to use delegated accounts which are keyed to the main account. This way users have a full control of everything with a single private key and they can distribute signed logic keys for specific NFT accounts (with burnt in Sender addresses).

**Comment by Alex99y** [comment]
Hello @solkimicreb ! Thank you for reporting this issue. Currently, MyAlgo Connect does not check for rekeyed address correctly but, the next version will do. We expect to release it in the next week.

**Comment by Alex99y** [comment]
Fixed!
