### ISSUE TITLE
myAlgoWallet.connect() is only returning 1 address even if you have multiple addresses present in your MyAlgoWallet.

### ISSUE THREAD

**Issue by raelyz** [randlabs/myalgo-connect#39]
Tried playing around with the API and noticed that an array of addressess is intended to be returned by the myAlgoConnect.connect() method. I have imported a 2nd address over but the method is only returning the first address at the moment. I'm not sure if this is intended behaviour and would appreciate some clarity as to how would I access the second address stored in the wallet.

**Comment by raelyz** [comment]
Probably session related, closed everything reopened and could view both addresses

**Comment by Alex99y** [comment]
Hello @raelyz ! One important thing is that MyAlgo Connect will only share accounts created by a mnemonic or ledger. (Multisig account or track account it is not supported).

**Comment by raelyz** [comment]
Hey @Alex99y! Thanks for pointing that out, if that is the case are there any intentions to include support for multisig/track accounts?

**Comment by Alex99y** [comment]
@raelyz Currently, we have no plan to share track accounts but multisig accounts yes. Do you mean by using Ledger Live it shows you more than one address?

**Comment by raelyz** [comment]
@Alex99y yup, Ledger Live shows me more than one address but myalgo wallet only shows me 1.

**Comment by Alex99y** [comment]
@raelyz Yes, because Ledger Live derivates more public keys. Currently, MyAlgo only gets the first derivation, and it is in our plan to support wallet HD from Ledger Wallet.
