### ISSUE TITLE
window is not defined when running on nextjs application

### ISSUE THREAD

**Issue by baart1989** [randlabs/myalgo-connect#47]
Hello! 

Trying to integrate your lib into nextjs application.
But i am getting 'window is not defined' error, which makes sense given SSR.

Any chance you can fix it somehow to support SSR or guide how to initialize the lib in nextjs app ?
Error is thrown here

`ReferenceError: window is not defined at Messenger._installListener (***/node_modules/@randlabs/communication-bridge/lib/messenger.js:144:3)`

**Comment by Alex99y** [comment]
Hello @baart1989 ! You need to import the library inside the `componentDidMount` or `useEffect` methods. That is because MAC uses `window` object from the browser and it's not defined outside browser the browser environment.
An example:
```js
const [ myAlgoConnect, setMyAlgoWallet ] = useState(null)
useEffect(() => {
        import('@randlabs/myalgo-connect')
        .then((MyAlgoConnect) => {
            const myAlgoWallet = new MyAlgoConnect.default()
            setMyAlgoWallet(myAlgoWallet)
        })
        .catch((err) => {
            console.log(err) // Something bad happened
        )}
}, []) // This should be execute once
```

**Comment by baart1989** [comment]
thank you @Alex99y that is really helpful!

**Comment by mzaatar** [comment]
Inspired by this response, for remix.run, you can use:

```typescript
let myAlgoObject: any

function loadMyAlgo(): Promise<MyAlgoConnect> {
    // dynamic import due to using `window` (not compatible with SSR)
    return import('@randlabs/myalgo-connect')
  }

  useEffect(() => {
    if (!myAlgoObject) {
      loadMyAlgo()
        .then((myAlgoConnect) => {
          myAlgoObject = new myAlgoConnect.default()
        })
        .catch((err) => {
          console.log(`Cannot initiate the MyAlgo Connector with error: ${err}`) // Something bad happened
        })
    }
  }, []) // This should be executed once
```
