### ISSUE TITLE
Report a display bug in myalgo web front-end

### ISSUE THREAD

**Issue by yuanzimu** [randlabs/myalgo-connect#51]
Hello, I encountered a display bug in front-end of myalgo wallet. As seems there is not a public respository about myalgo webpages, I will describe this bug here.

The situation is: 
1.  I created a wallet in myalgo, and sent some $algo (let n1 denote its number) to this wallet address  $a1;
2.  Then, I tried to call py-algorand-sdk [https://github.com/algorand/py-algorand-sdk](url) to transfer all n1 $algo in $a1 to another wallet $a2 with the code:
`params = algodclient.suggested_params()`
`txn = transaction.PaymentTxn(from_addr, params, to_addr, amount, asset_id, close_assets_to=to_addr)`
`algodclient.send_transaction(txn.sign(from_key))`
where `from_addr=$a1` ,  `to_addr=$a2`,  and  `close_assets_to`  is set for emptying wallet $a1;
3.  However, the dispaly balance of $a1 would remain n1 after several hours of emptying, not synchronized with the algorand network, in the myalgo webpage;

4. As I repeated similar calling processes for several times, the situation remained the same. Here are some screenshots:
![wallet1274](https://user-images.githubusercontent.com/17566632/145085744-c150f2b7-4030-464c-8690-5beb92d6f0c9.png)
![wallet1275](https://user-images.githubusercontent.com/17566632/145085761-94ff14cd-0209-4200-90cb-3e896e5ab363.png)
![wallet1276](https://user-images.githubusercontent.com/17566632/145085781-19d82f19-ec39-4683-9e68-623be43446e6.png)

5. BTW,  when I chose to left some $algo in myalgo wallet,  the display is correct:
![wallet1](https://user-images.githubusercontent.com/17566632/145087272-d181c64e-dba5-422e-a0ab-817ce3acf312.png)

  So I guess there is some condition missing considered in balance display.

**Comment by Alex99y** [comment]
Hello @yuanzimu Thank you a lot for reporting this issue. The fix will be deployed this week
