### ISSUE TITLE
sign 2 batches of tx groups in a roll

### ISSUE THREAD

**Issue by Mine77** [randlabs/myalgo-connect#53]
Hi there,

I have a large size array of txns that I would like to sign and I've divided them into smaller arrays with a length of 16 (due to the tx group size limitation). It's something like this:
![image](https://user-images.githubusercontent.com/11781031/148213982-5db710de-bb69-479b-bb11-22530bb18d86.png)

and what I wanna do next is to sign this array of tx group in sequence:
```
let signedTxg = new Array(txgg.length); // txgg here is the chunked array above
for (let i = 0; i < txgg.length; i++) {
  signedTxg[i] = await walletContext.myAlgoConnect.signTransaction(
    txgg[i].map((txn) => txn.toByte())
  );
  console.log(txgg[i]);
}
console.log(signedTxg);
```

The expected behavior is when I close the first popup, the second popup can show up.

However, the first popup did work and I did get the signed txgroup while the second one doesn't show up and I got an error message like this: `PopupOpenError: Can not open popup window - blocked`

I'm using nextjs and the code is triggered by a button onclick.

I tried to setTimeout after the signTransaction function returns but it didn't work.

I got the myAlgoConnect instance from the contextAPI and I'm wondering if this is an issue?
Should I use a new instance everytime I signTx? 

Thanks in advance.

**Comment by Mine77** [comment]
ah I see it's blocked by my browser.
I should do error handling.
Thanks!

**Comment by Alex99y** [comment]
Hello @Mine77 ! Yes, every MyAlgoConnect method must be triggered by an onClick event and this event cannot be reused.
