### ISSUE TITLE
Feature proposal: Create and Verify Zero Value Transactions

### ISSUE THREAD

**Issue by hutch120** [randlabs/myalgo-connect#59]
The core idea is that we want to build UX systems where we can verify ownership of an account (and by inference ASAs) without bothering the user with constant popups and without making the user pay for the privilege.

There is a forum discussion thread which is part of the way there, it achieves the verification step https://forum.algorand.org/t/custody-verification-in-algorand/1422/9 and we are starting to see this implemented in the wild such as this site https://blackbook.originalsonly.io/

My feature proposal is for two additional SDK function calls to make this process much simpler:

1) `createZeroValueTxn(noteId):txn` which creates a signed transaction with the `noteId` (off-chain) and can easily be sent in a JSON payload (byte array?)
2) `verifyZeroValueTxn(txn, noteId):bool` which takes the `txn` and returns a boolean that verifies the a zero value signed txn includes the `noteId` field (new context, e.g. could be on another client, or node server).

Importantly is it possible to achieve this without a popup, perhaps after an initial unlock, in order to create smooth UX experiences?

Probably there would also be a need to add an opt-in flag to allow this (maybe per account).

Pls let me know if this makes sense and if it has merit I'm happy to help with a PR.

Also, if this is not the right place for a feature suggestion discussion pls let me know where (discord?)

Additional references:
- https://forum.algorand.org/t/whats-the-most-up-to-date-way-2022-to-sign-via-walletconnect-and-verify-via-algosdk/5730
- https://forum.algorand.org/t/verify-signed-transaction-for-a-given-address/5922
- https://forum.algorand.org/t/custody-verification-in-algorand/1422/9
- https://forum.algorand.org/t/verify-signature-on-signed-transaction/3209

**Comment by hutch120** [comment]
After thinking on this a bit more, there appears to be a fairly simple way to do a basic initial onboarding by generating a hashed signed transaction. (although I still think the above functions would be useful)

Essentially, we can ask the user to sign a zero value transaction (off-chain) and, assuming all params are identical each request, the result is always the same. So, we can put some generated key into the note field, and use the hash of the signature as the (initial/temporary/single factor) web2 password.

Code to generate the "password" might look something like this:

```
import MyAlgo from '@randlabs/myalgo-connect'
import algosdk from 'algosdk'
import sha256 from 'crypto-js/sha256'
import CryptoJS from 'crypto-js'

async function GenerateAccountHash() {
  const address = 'Account returned by myalgo-connect'
  const to = 'Your platform account'
  const noteStr = 'abc123'
  const note = Uint8Array.from(Array.from(noteStr).map((letter) => letter.charCodeAt(0)))
  const txn = algosdk.makeAssetTransferTxnWithSuggestedParamsFromObject({
    suggestedParams: {
      fee: 0,
      firstRound: 1,
      flatFee: false,
      genesisHash: 'SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=',
      genesisID: 'v1.0',
      lastRound: 1
    },
    from: address,
    to,
    assetIndex: 1,
    amount: 0,
    note
  })
  let signedTxn = await myAlgoWallet.signTransaction(txn.toByte())
  const signedTxnSha256 = sha256(signedTxn.blob).toString(CryptoJS.enc.Hex)
  return signedTxnSha256 
}
```

I guess with some effort an "evil" player could construction a fishing website could also ask users to sign a zero value txn with the same params and note field, and that sha256 hashed would be the password, so, I guess at some point another factor like 2FA would add another level of security.

I will close this issue, but if anyone would like to provide feedback... is this a good/bad/dumb solution, I'd love to get an idea of what others are doing (if anything).

**Comment by Alex99y** [comment]
Hello @hutch120 ! I'm sorry for my late reply. Thanks a lot for your proposal, but it's not possible its implementation.
MyAlgo Connect library is a tool that allows communication between the dApp and MyAlgo Connect popups. In order to sign transactions, MyAlgo Connect needs to have access to the user storage and this is impossible without using popups, it needs to execute in the context of `https://wallet.myalgo.com`. Moreover, the stored private key is encrypted and we need the user's password to decrypt it.

However, it's in our plans to integrate sign message operation to MyAlgo Connect.
