### ISSUE TITLE
Is it possible to sign multisig transactions?

### ISSUE THREAD

**Issue by Patryqss** [randlabs/myalgo-connect#67]
As the title says. I found no option to sign a multisig transaction on myAlgo. 

For reference, in AlgoSigner, during the signing process, there is a possibility to pass an optional parameter `msig`, which specifies that a txn will be a multisig one and provides all needed data for it (required adresses, threshold & version). I didn't find anything like that here. `signTransaction` function only accepts transaction or an array of transactions as first parameter and signOptions as a second one but those options are just limited to `overrideSigner`, which I believe, has nothing to do with multisig transactions.

So, is there any way to do it? If not, it would be nice to implement this feature

**Comment by M-Picco** [comment]
Hi @Patryqss, Multisig transaction signatures, either partial or complete, are not yet supported. However, there are plans in the near future to add support for them.

As you mentioned, `overrideSigner` has nothing to do with multisig txs. The option forces the transaction to be signed with a specific account which might not be the one in the `from` field.

**Comment by ivanschuetz** [comment]
Hi @M-Picco, just to confirm, this would include all transaction types, and the apps wouldn't have to do anything other than have the first user sign the transactions, correct? From there, the other users sign in MyAlgo, and when it's complete, MyAlgo submits them to the network?
