### ISSUE TITLE
Unable to override signer when original sender address is not in wallet

### ISSUE THREAD

**Issue by petitnau** [randlabs/myalgo-connect#69]
It seems that if I want to sign a transaction using the `overrideSigner` option of the `signTransaction` method, I need to have the original address that is present in the `from`/`sender` field as an account in MyAlgoWallet.

Here is an example to reproduce the error. ACC1 is an account not present in MyAlgoWallet, while ACC2 is an account that is present.
```javascript
const ACC1 = "..."
const ACC2 = "..."

const node = 'https://node.testnet.algoexplorerapi.io';

const myAlgoConnect = new MyAlgoConnect({ disableLedgerNano: false,  });
myAlgoConnect.connect();

const algodClient = new algosdk.Algodv2('', node, '');

const params = await algodClient.getTransactionParams().do();
const txn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
  suggestedParams: { ...params },
  from: ACC1,
  to: ACC1,
  amount: 10,
});

const signedTxn = await myAlgoConnect.signTransaction(txn.toByte(), { overrideSigner  : ACC2 });
```
```
Error: Account does not exist in the storage
    at MyAlgoConnect.signTransaction (main.js:356:1)
```
If instead both ACC1 and ACC2 are added onto the wallet, then everything works fine.

**Comment by M-Picco** [comment]
Hey @petitnau! Thank you for reporting this issue. We'll be taking a look into this.

**Comment by gidonkatten** [comment]
would be great if this could be fixed

**Comment by M-Picco** [comment]
I'm closing this since a fix has been deployed with the last release
